### ISSUE TITLE
Bug: something is wrong with the snooze setting

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [vicolo-dev/chrono#332]
**Describe the bug**
Unfortunately I don't yet know how to reproduce but I'm positive something funky is going on.

My alarms all have the snooze toggled on, but when it rings, sometimes I have a choice between dismiss and snooze, sometimes I just see dismiss. I have like 4 alarms and it seems to be randomly active for each.

Toggling back and forth the button seems to fix it for one alarm, or not, because a few days after it seems to be toggle off again (even though the button always was set to on).

It's all very confusing and I apologize for such an empty bug report but I'm reasonably confident there's an issue with how snooze settings are stored.

**Smartphone Information**
 - Device: [e.g. Pixel 4a 5G on GrapheneOS]
 - OS: [e.g. Android 14]
 - App version [e.g. 0.5.1]

**Additional context**
I think you should maybe add some asserts here and there and it would help us narrow down what's going on maybe?

**Comment by AhsanSarwar45** [comment]
Hey, thanks for the report. Are you sure its not the max snoozes setting coming to play? By default, you can only snooze an alarm 3 times consecutively. After that, snooze button won't appear. Maybe the bug is that setting isn't getting reset after alarm is dismissed?

**Comment by thiswillbeyourgithub** [comment]
Totally possible. I'm not sure how I should test that.

**Comment by onnyyonn** [comment]
I am facing this issue as well. I never see the snooze option, despite having snooze enabled in the alarm settings.

> By default, you can only snooze an alarm 3 times consecutively. After that, snooze button won't appear. Maybe the bug is that setting isn't getting reset after alarm is dismissed?

I think this is what is happening. I usually keep editing the same alarm. To test this, I created a few new alarms with different numbers of max snooze. Every time, snooze appears until I reach that number of snoozes. And then they stopped. Even after dismissing, and editing them to start a new alarm, snooze did not come back for them.

**Comment by azeem-io** [comment]
> I am facing this issue as well. I never see the snooze option, despite having snooze enabled in the alarm settings.
> 
> > By default, you can only snooze an alarm 3 times consecutively. After that, snooze button won't appear. Maybe the bug is that setting isn't getting reset after alarm is dismissed?
> 
> I think this is what is happening. I usually keep editing the same alarm. To test this, I created a few new alarms with different numbers of max snooze. Every time, snooze appears until I reach that number of snoozes. And then they stopped. Even after dismissing, and editing them to start a new alarm, snooze did not come back for them.

Thanks, I have discovered the bug, should be fixed for the next verision.

**Comment by AhsanSarwar45** [comment]
@onnyyonn @thiswillbeyourgithub Can you guys test with [0.6.0-beta1](https://github.com/vicolo-dev/chrono/releases/tag/v0.6.0-beta1)?

**Comment by onnyyonn** [comment]
Tested the latest beta. Unfortunately I could still reproduce the bug.

**Comment by AhsanSarwar45** [comment]
> Tested the latest beta. Unfortunately I could still reproduce the bug.

Did you try with a new alarm? If so, can you detail the exact steps to reproduce your issue?

**Comment by onnyyonn** [comment]
My bad. I did not create a new alarm. I tested this again, and the bug seems to be resolved now. Thanks.

**Comment by AhsanSarwar45** [comment]
Thats great to hear. If you face the issue again, feel free to reopen this.
